/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 vista.glb -T 
Files: vista.glb [255.15KB] > C:\Users\domin\OneDrive\Bureau\WebDev\Vista_Studio\public\models\vista-transformed.glb [15.24KB] (94%)
*/

import React from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import * as THREE from 'three';

export function Vista(props) {
  const matcapTexture = useTexture('./images/textures/mat1.png');
  const { nodes } = useGLTF('./models/vista-transformed.glb');

  const bodyMaterial = new THREE.MeshPhongMaterial({
    map: matcapTexture,
    color: 'lightBlue',
  });
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Vista.geometry}
        material={bodyMaterial}
        position={[0, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={50}
      />
    </group>
  );
}

useGLTF.preload('./models/vista-transformed.glb');
