/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MacbookProAN.glb -T 
Files: MacbookProAN.glb [28.1MB] > C:\Users\domin\OneDrive\Bureau\WebDev\Vista_Studio\public\models\MacbookProAN-transformed.glb [1.38MB] (95%)
*/

import React from 'react';
import { OrbitControls, useGLTF } from '@react-three/drei';

export function Macbook(props) {
  const group = React.useRef();
  const { nodes, materials } = useGLTF('./models/MacbookProAN-transformed.glb');
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={55}
      rotation={[0, 30, 0]}
      position={[10, -10, 5]}
    >
      <OrbitControls
        autoRotate
        enableRotate={false}
        enablePan={false}
        enableZoom={false}
      />
      <group name="Scene">
        <group
          name="Cube013"
          position={[-0.277, 0.064, -0.016]}
          rotation={[1.571, 1.555, -1.571]}
          scale={[0.773, 0.36, 0.773]}
        >
          <mesh
            name="Cube029"
            geometry={nodes.Cube029.geometry}
            material={materials.RGB}
          />
          <mesh
            name="Cube029_1"
            geometry={nodes.Cube029_1.geometry}
            material={materials.PaletteMaterial002}
          />
          <mesh
            name="Cube029_2"
            geometry={nodes.Cube029_2.geometry}
            material={materials['key.002']}
          />
          <mesh
            name="Cube029_3"
            geometry={nodes.Cube029_3.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            name="Cube029_4"
            geometry={nodes.Cube029_4.geometry}
            material={materials.PaletteMaterial003}
          />
          <mesh
            name="Cube029_5"
            geometry={nodes.Cube029_5.geometry}
            material={materials.PaletteMaterial004}
          />
          <mesh
            name="Cube029_6"
            geometry={nodes.Cube029_6.geometry}
            material={materials.PaletteMaterial005}
          />
          <mesh
            name="Cube029_7"
            geometry={nodes.Cube029_7.geometry}
            material={materials.metal}
          />
          <mesh
            name="Cube029_8"
            geometry={nodes.Cube029_8.geometry}
            material={materials.screen}
          />
          <mesh
            name="Cube029_9"
            geometry={nodes.Cube029_9.geometry}
            material={materials.PaletteMaterial006}
          />
          <mesh
            name="Cube029_10"
            geometry={nodes.Cube029_10.geometry}
            material={materials.PaletteMaterial007}
          />
          <mesh
            name="Cube029_11"
            geometry={nodes.Cube029_11.geometry}
            material={materials.PaletteMaterial008}
          />
          <mesh
            name="Cube029_12"
            geometry={nodes.Cube029_12.geometry}
            material={materials['Apple-logo']}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('./models/MacbookProAN-transformed.glb');
